# Generated by Django 2.1 on 2018-08-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('asin', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('image', models.URLField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('title', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=False)),
                ('amount', models.BigIntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=14)),
                ('length', models.DecimalField(decimal_places=2, max_digits=14)),
                ('width', models.DecimalField(decimal_places=2, max_digits=14)),
                ('height', models.DecimalField(decimal_places=2, max_digits=14)),
                ('changed_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
